### ISSUE TITLE
Repeated warn for log files that don't exist yet

### ISSUE THREAD

**Issue by pmcevoy** [efontana/TimberWinR#2]
There are many situations where Timber would be configured to watch certain log files, and that those log files may not exist.  Timber floods it's own log files with WARN messages for log files that don't exist:

```
015-01-26 09:41:39.1494|WARN|TimberWinR.Inputs.LogsListener|Error executing query: Cannot open <from-entity>: Error opening files: Error opening file "C:\Logs\Edts\Edts\Edts.MockOperator.Api.log": The system cannot find the file specified. [The system cannot find the file specified.]
```
- Timber is configured, but the application hasn't been installed or started
- The application is uninstalled and the log removed
- The application does not create a log file until an error happens (I know, this is bad but we have legacy apps that only log problems)

In my opinion, Timber should not be so verbose if a log file does not exist: one warning is enough if the file becomes or is unavailable.  If the file becomes available later, then a single indication that it has been picked up would be great.  But flooding the logs with a continuous stream is alarming and drowns out other legitimate errors

**Comment by efontana** [comment]
I agree, this needs to be fixed.
